### ISSUE TITLE
Yolov7

### ISSUE THREAD

**Issue by dragan07-07** [cj-mills/onnx-directml-unity-tutorial#1]
Hi, can I use this plugin to load Yolov7-Tiny?

**Comment by ilanb** [comment]
Hi, Tried to use on Unity OSX 
error when I play in editor, all DLL placed in plugin folder like tutorial

DllNotFoundException: ONNX_YOLOX_DLL assembly:<unknown assembly> type:<unknown type> member:(null)
ObjectDetector.UploadTexture (UnityEngine.Texture2D texture) (at Assets/_MAIN/_ONNX-YOLOX/Scripts/ObjectDetector.cs:553)
ObjectDetector.Update () (at Assets/_MAIN/_ONNX-YOLOX/Scripts/ObjectDetector.cs:680)

Regards,
